# --------------------------------------------------------------
# ESPHome - Tele-information
# --------------------------------------------------------------
# Option tarifaire: Heure Pleine / Heure Creuse
#
# esphome run tele-information-HPHC.yaml

esphome:
  name: tele-information-hphc
  friendly_name: Télé-information HP/HC

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  logs:
    uart: ERROR

wifi:
  ssid: "SSID"
  password: "SSID_PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Téléinfo Fallback Hotspot"
    password: "sEy9m3EuGqQc"

# Web Server: https://esphome.io/components/web_server.html
web_server:
  local: true
  port: 80
  auth:
    username: "admin"
    password: "admin"
  # Turn on or off the log feature inside webserver
  log: true

uart:
  id: uart_bus
  rx_pin: GPIO21
  tx_pin: GPIO17
  baud_rate: 1200
  parity: EVEN
  data_bits: 7

teleinfo:
  id: teleinformation
  update_interval: 5s
  historical_mode: true

sensor:
  - platform: teleinfo
    tag_name: "ISOUSC"
    id: isousc
    name: "Intensité souscrite (ISOUSC)"
    unit_of_measurement: A
    teleinfo_id: teleinformation
    state_class: measurement
    device_class: current
  - platform: teleinfo
    tag_name: "HCHC"
    name: "Heures Creuses (HCHC)"
    unit_of_measurement: "kWh"
    teleinfo_id: teleinformation
    accuracy_decimals: 3
    state_class: total_increasing
    device_class: energy
    filters:
      - multiply: 0.001
  - platform: teleinfo
    tag_name: "HCHP"
    name: "Heures Pleines (HCHP)"
    unit_of_measurement: "kWh"
    teleinfo_id: teleinformation
    accuracy_decimals: 3
    state_class: total_increasing
    device_class: energy
    filters:
      - multiply: 0.001
  - platform: teleinfo
    tag_name: "IINST"
    id: iinst
    name: "Intensité instantanée (IINST)"
    unit_of_measurement: A
    teleinfo_id: teleinformation
    state_class: measurement
    device_class: current
    accuracy_decimals: 2
  - platform: teleinfo
    tag_name: "IMAX"
    id: imax
    name: "Intensité maximale appelée (IMAX)"
    unit_of_measurement: A
    teleinfo_id: teleinformation
    state_class: measurement
    device_class: current
    accuracy_decimals: 2
  - platform: teleinfo
    tag_name: "PAPP"
    name: "Puissance apparente (PAPP)"
    unit_of_measurement: "W"
    teleinfo_id: teleinformation
    accuracy_decimals: 0
    state_class: measurement
    device_class: power

text_sensor:
  - platform: teleinfo
    tag_name: "ADCO"
    name: "Adresse du compteur (ADCO)"
    teleinfo_id: teleinformation
  - platform: teleinfo
    tag_name: "OPTARIF"
    name: "Option tarifaire choisie (OPTARIF)"
    teleinfo_id: teleinformation
  - platform: teleinfo
    tag_name: "PTEC"
    name: "Période Tarifaire en cours (PTEC)"
    teleinfo_id: teleinformation
  - platform: teleinfo
    tag_name: "HHPHC"
    name: "Horaire Heures Pleines Heures Creuses (HHPHC)"
    teleinfo_id: teleinformation